[project]
name = "web3-favourites"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.1",
    "vyper>=0.4.1",
    "web3>=7.8.0",
]
